# ---------------------- #
# ---- SDR Profiles ---- #
# ---------------------- #

[sdr]
profile-desc=sdr
profile-cond=get("video-params/primaries")~="bt.2020" and get("user-data/display-info/hdr-supported")=="false"
target-colorspace-hint=no
target-prim=bt.709
target-trc=bt.1886
tone-mapping=spline
inverse-tone-mapping=yes
profile-restore=copy

[hdr-to-sdr]
profile-desc=hdr to sdr
profile-cond=get("video-params/primaries")=="bt.2020" and get("user-data/display-info/hdr-supported")=="false"
target-colorspace-hint=no
tone-mapping=auto
tone-mapping-param=1.0
tone-mapping-max-boost=1.0
gamut-mapping-mode=auto
hdr-contrast-recovery=0.30
hdr-contrast-smoothness=3.5
hdr-compute-peak=auto
hdr-peak-percentile=99.995
hdr-peak-decay-rate=100
hdr-scene-threshold-low=5.5 
hdr-scene-threshold-high=10
allow-delayed-peak-detect=no
profile-restore=copy


# ---------------------- #
# ---- HDR Profiles ---- #
# ---------------------- #

[hdr]
profile-desc=hdr
profile-cond=get("video-params/primaries")=="bt.2020" and get("user-data/display-info/hdr-supported")=="true"
target-trc=pq
target-prim=bt.2020
target-colorspace-hint=yes
hdr-compute-peak=auto
tone-mapping=spline
inverse-tone-mapping=yes
profile-restore=copy

[sdr-2-hdr]
profile-desc=sdr to hdr
profile-cond=get("video-params/primaries")~="bt.2020" and get("user-data/display-info/hdr-supported")=="true"
target-trc=pq
target-prim=bt.2020
target-colorspace-hint=yes
hdr-compute-peak=auto
tone-mapping=spline
inverse-tone-mapping=yes
profile-restore=copy