# ------------------------- #
# ---- Shader Profiles ---- #
# ------------------------- #

[artcnn]
profile-desc=Artoriuz Convolutional Neural Network
glsl-shaders-clr
glsl-shaders-append="~~/shaders/ArtCNN_C4F16_DN.glsl"
glsl-shaders-append="~~/shaders/SSimSuperRes.glsl"
glsl-shaders-append="~~/shaders/CfL_Prediction.glsl"
profile-restore=copy

[fsrcnnx]
profile-desc=Fast Super-Resolution Convolutional Neural Network Extended
glsl-shaders-clr
glsl-shaders-append="~~/shaders/FSRCNNX_x2_8-0-4-1.glsl"
glsl-shaders-append="~~/shaders/SSimSuperRes.glsl"
glsl-shaders-append="~~/shaders/CfL_Prediction.glsl"
profile-restore=copy

[fsr]
profile-desc=AMD FidelityFX Super Resolution
glsl-shaders-clr
glsl-shaders-append="~~/shaders/FSR.glsl"
glsl-shaders-append="~~/shaders/CfL_Prediction.glsl"
profile-restore=copy

[ravu]
profile-desc=Rapid and Accurate Video Upscaling
glsl-shaders-clr
glsl-shaders-append="~~/shaders/ravu-zoom-ar-r3.hook"
glsl-shaders-append="~~/shaders/SSimSuperRes.glsl"
glsl-shaders-append="~~/shaders/CfL_Prediction.glsl"
profile-restore=copy

[nnedi3]
profile-desc=Neural Network Edge Directed Interpolation
glsl-shaders-clr
glsl-shaders-append="~~/shaders/nnedi3-nns64-win8x4.hook"
glsl-shaders-append="~~/shaders/SSimSuperRes.glsl"
glsl-shaders-append="~~/shaders/CfL_Prediction.glsl"
profile-restore=copy

[ssim]
profile-desc=SSimDownscaler
glsl-shaders-clr
glsl-shaders-append="~~/shaders/SSimSuperRes.glsl"
glsl-shaders-append="~~/shaders/CfL_Prediction.glsl"
glsl-shaders-append="~~/shaders/SSimDownscaler.glsl"
linear-downscaling=no
profile-restore=copy

[noise-static]
profile-desc=Noise Static Luma and Chroma
glsl-shaders-append="~~/shaders/noise_static_luma.hook"
glsl-shaders-append="~~/shaders/noise_static_chroma.hook"
profile-restore=copy


# -------------------------------- #
# ---- Video Quality Profiles ---- #
# -------------------------------- #

[sd]
profile-desc=sd
profile-cond=height<720
profile=fsrcnnx
# profile=noise-static
profile-restore=copy

[hd]
profile-desc=hd
profile-cond=height==720
profile=fsrcnnx
# profile=noise-static
profile-restore=copy

[fhd]
profile-desc=fhd-60
profile-cond=height==1080
profile=fsrcnnx
# profile=noise-static
profile-restore=copy

[qhd]
profile-desc=qhd-30
profile-cond=height==1440
profile=fsrcnnx
# profile=noise-static
profile-restore=copy

[uhd]
profile-desc=uhd-30
profile-cond=height>=2160
profile=ssim
deband=no
profile-restore=copy