# --- Shader Profiles --- #

Ctrl+1      no-osd apply-profile "artcnn"			# event: click	
Ctrl+2      no-osd apply-profile "fsrcnnx"			# event: click	
Ctrl+3      no-osd apply-profile "fsr"				# event: click	
Ctrl+4      no-osd apply-profile "ravu"				# event: click	
Ctrl+5      no-osd apply-profile "nnedi3"			# event: click		
Ctrl+6      no-osd apply-profile "ssim"				# event: click	
Ctrl+9      no-osd apply-profile "noise-static"		# event: click	
Ctrl+0      no-osd change-list glsl-shaders clr ""; script-message profile_notifier reset ; show-text "GLSL shaders cleared"	# event: click	