_           script-message-to mpvnet open-clipboard  # File > Open URL or file from clipboard
Ctrl+v      script-message-to mpvnet open-clipboard append  # File > Add files/URLs to playlist from clipboard
_           quit                          # File > Exit
_           stop                          # Playback > Stop
_           add chapter 1                 # Navigate > Next Chapter
_           add chapter -1                # Navigate > Previous Chapter
_           seek 5                        # Navigate > Jump 5 sec forward
_           seek -5                       # Navigate > Jump 5 sec backward
_           seek 30                       # Navigate > Jump 30 sec forward
_           seek -30                      # Navigate > Jump 30 sec backward
_           seek 300                      # Navigate > Jump 5 min forward
_           seek -300                     # Navigate > Jump 5 min backward
Ctrl+-      add video-zoom -0.1            # Pan & Scan > Decrease Size
Ctrl+=      add video-zoom 0.1            # Pan & Scan > Increase Size
_           add panscan -0.1              # Pan & Scan > Decrease Height
_           add panscan 0.1               # Pan & Scan > Increase Height
_           async screenshot              # Video > Take Screenshot
_           async screenshot video        # Video > Take Screenshot without subtitles
_           cycle deinterlace             # Video > Toggle Deinterlace
_           cycle-values video-aspect-override 16:9 4:3 2.35:1 0 -1  # Video > Change Aspect Ratio
_           script-message-to mpvnet cycle-audio  # Audio > Next Track
_           add audio-delay 0.1           # Audio > Delay +0.1
_           add audio-delay -0.1          # Audio > Delay -0.1
_           script-message-to mpvnet cycle-subtitles  # Subtitle > Next Track
_           cycle sub-visibility          # Subtitle > Toggle Visibility
[           add sub-delay -0.1            # Subtitle > Delay -0.1
]           add sub-delay 0.1             # Subtitle > Delay +0.1
{           add sub-pos -1                # Subtitle > Move Up
}           add sub-pos 1                 # Subtitle > Move Down
_           multiply speed 1/1.1          # Speed > -10%
_           multiply speed 1.1            # Speed > +10%
_           multiply speed 0.5            # Speed > Half
_           multiply speed 2.0            # Speed > Double
_           script-binding select/select-playlist  # View > Playlist
_           script-binding select/select-playlist  # View > On-Screen Menu > Playlist
_           script-binding select/select-aid  # View > On-Screen Menu > Audio Tracks
_           script-binding select/select-sid  # View > On-Screen Menu > Subtitle Tracks
_           script-binding select/select-secondary-sid  # View > On-Screen Menu > Secondary Subtitle
_           script-binding select/select-audio-device  # View > On-Screen Menu > Audio Devices
_           cycle border                  # Window > Toggle Border
b           ab-loop                       # Tools > Set/clear A-B loop points
_           quit-watch-later              # Tools > Exit Watch Later
_           script-message-to mpvnet shell-execute https://github.com/stax76/awesome-mpv  # Help > awesome-mpv
_           quit                          # Exit
MBTN_MID    script-message-to mpvnet play-pause  # Play/Pause
MBTN_MID    script-message-to mpvnet play-pause  # Play/Pause
MBTN_MID    script-message-to mpvnet play-pause  # Play/Pause
MBTN_MID    script-message-to mpvnet play-pause  # Play/Pause
_           seek  60                      # Forward
_           seek -60                      # Backward
_           quit                          # Exit
K           script-binding select/context-menu
