vidscale=auto
persistent_overlay=yes
redraw_delay=1

font=Inconsolata
font_mono=Inconsolata
border_size=1

plot_vsync_ratio=yes
plot_vsync_jitter=yes
plot_perfdata=yes
plot_cache=yes
plot_tonemapping_lut=yes