
_           quit                          # File > Exit
MBTN_MID    script-message-to mpvnet play-pause  # Play/Pause
MBTN_MID    script-message-to mpvnet play-pause  # Play/Pause
MBTN_MID    script-message-to mpvnet play-pause  # Play/Pause
MBTN_MID    script-message-to mpvnet play-pause  # Play/Pause
j           revert-seek                   # Undo previous (or marked) seek
h           revert-seek mark              # Mark position for revert-seek
Esc         ignore                        # Ignore left mouse button
#Ignore left mouse button
MBTN_Right script-message-to mpvnet show-menu
