_           script-message-to mpvnet open-clipboard  # File > Open URL or file from clipboard
Ctrl+v      script-message-to mpvnet open-clipboard append  # File > Add files/URLs to playlist from clipboard
Alt+q       quit                          # File > Exit
_           seek 5                        # Navigate > Jump 5 sec forward
_           seek -5                       # Navigate > Jump 5 sec backward
_           seek 30                       # Navigate > Jump 30 sec forward
_           seek -30                      # Navigate > Jump 30 sec backward
_           seek 300                      # Navigate > Jump 5 min forward
_           seek -300                     # Navigate > Jump 5 min backward
_           script-message-to mpvnet cycle-audio  # Audio > Next Track
_           script-message-to mpvnet cycle-subtitles  # Subtitle > Next Track
_           cycle sub-visibility          # Subtitle > Toggle Visibility
_           add sub-pos -1                # Subtitle > Move Up
_           add sub-pos 1                 # Subtitle > Move Down
_           script-binding select/select-playlist  # View > Playlist
_           script-binding select/select-playlist  # View > On-Screen Menu > Playlist
_           script-binding select/select-secondary-sid  # View > On-Screen Menu > Secondary Subtitle
_           cycle border                  # Window > Toggle Border
_           seek  60                      # Forward
_           seek -60                      # Backward


# --- Playback --- #
c           revert-seek                   # Jump to Mark
v           revert-seek mark              # Mark Position
LEFT        seek  -5 ; show-text "${osd-ass-cc/0}{\\an5}{\\fs20}<<   5s   <<"  # Seek 5s backward
RIGHT       seek   5 ; show-text "${osd-ass-cc/0}{\\an5}{\\fs20}>>   5s   >>"  # Seek 5s forward
z           seek  -5 ; show-text "${osd-ass-cc/0}{\\an5}{\\fs20}<<   5s   <<"  # Seek 5s backward
x           seek   5 ; show-text "${osd-ass-cc/0}{\\an5}{\\fs20}>>   5s   >>"  # Seek 5s forward
KP1         seek -30 ; show-text "${osd-ass-cc/0}{\\an5}{\\fs20}<<   30s   <<"  # Seek 30s backward
KP3         seek  30 ; show-text "${osd-ass-cc/0}{\\an5}{\\fs20}>>   30s   >>"  # Seek 30s forward
KP4         seek -60 ; show-text "${osd-ass-cc/0}{\\an5}{\\fs20}<<   60s   <<"  # Seek 60s backward
KP6         seek  60 ; show-text "${osd-ass-cc/0}{\\an5}{\\fs20}>>   60s   >>"  # Seek 60s forward
KP7         playlist-prev ; script-message playlistmanager show playlist 2  # Next File
KP9         playlist-next ; script-message playlistmanager show playlist 2  # Previous File

# --- Custom Menu --- #
b           script-binding autosub/download_subs #custom-menu: Download Subs 1
B           script-binding autosub/download_subs2 #custom-menu: Download Subs 2
f           script-binding quality_menu/video_formats_toggle  #custom-menu: Show Video Formats
Alt+f       script-binding quality_menu/audio_formats_toggle  #custom-menu: Show Audio Formats
F8          script-message playlistmanager show playlist toggle  #custom-menu: Toggle Playlist
R           run "cmd.exe" /d /c start "" ${path}; quit-watch-later  #custom-menu: Hot Restart
B           script-binding autosub/download_subs  #custom-menu: Download Subs
MBTN_Right  script-message-to mpvnet show-menu

# --- Shader Profiles --- #
CTRL+1      no-osd apply-profile "anime-hq-a"
CTRL+2		no-osd apply-profile "anime-hq-b"
CTRL+3		no-osd apply-profile "anime-hq-c"
CTRL+0 		no-osd change-list glsl-shaders clr ""; show-text "GLSL shaders cleared"
