# ---------------------- #
# ---- HDR Profiles ---- #
# ---------------------- #

# [hdr-video]
# profile-desc=Configuration for HDR displays
# profile-cond=get("user-data/display-info/hdr-supported")=="true"
# target-trc=pq
# target-prim=bt.2020
# target-colorspace-hint=yes
# target-peak=auto 
# hdr-compute-peak=auto
# profile-restore=copy

[hdr-display]
profile-desc=Passthrough parameters for HDR displays
profile-cond=get("user-data/display-info/hdr-supported")=="true"
profile-restore=copy
icc-profile=""
icc-profile-auto=no
target-colorspace-hint=auto
target-colorspace-hint-mode=target
inverse-tone-mapping=no
target-prim=auto
target-trc=auto
target-peak=auto
target-contrast=auto

[hdr-video]
profile-desc=Configuration for HDR video content
profile-cond=get("video-params/max-luma") > 203
profile-restore=copy
target-colorspace-hint=auto
target-colorspace-hint-mode=target
blend-subtitles=no
deband=no
vf=""

[sdr-2-hdr]
profile-desc=Configuration to handle SDR video content on HDR displays
profile-cond=get("video-params/primaries")~="bt.2020" and get("user-data/display-info/hdr-supported")=="true"
target-trc=pq
target-prim=bt.2020
target-colorspace-hint=yes
target-peak=400 
tone-mapping=spline
inverse-tone-mapping=yes


# ---------------------- #
# ---- SDR Profiles ---- #
# ---------------------- #

[hdr-to-sdr]
profile-desc=Configuration to handle HDR video content on SDR displays
profile-cond=get("video-params/primaries")=="bt.2020" and get("user-data/display-info/hdr-supported")=="false"
target-colorspace-hint=no
tone-mapping=auto
tone-mapping-param=1.0
tone-mapping-max-boost=1.0
gamut-mapping-mode=auto
hdr-contrast-recovery=0.30
hdr-contrast-smoothness=3.5
hdr-compute-peak=auto
hdr-peak-percentile=99.995
hdr-peak-decay-rate=100
hdr-scene-threshold-low=5.5 
hdr-scene-threshold-high=10
allow-delayed-peak-detect=no
profile-restore=copy

[sdr]
profile-desc=Configuration for SDR displays
profile-cond=get("user-data/display-info/hdr-supported")=="false"
target-colorspace-hint=no
target-prim=bt.709
target-trc=bt.1886
tone-mapping=spline
inverse-tone-mapping=yes
profile-restore=copy