# ------------------------- #
# ---- Shader Profiles ---- #
# ------------------------- #

[ravu]
profile-desc=Rapid and Accurate Video Upscaling
glsl-shaders-append="~~/shaders/ravu-zoom-ar-r3.hook"
glsl-shaders-append="~~/shaders/KrigBilateral.glsl"
dscale=mitchell
cscale=ewa_lanczos
linear-downscaling=yes

[fsrcnnx]
profile-desc=Fast Super-Resolution Convolutional Neural Network Extended
glsl-shaders-append="~~/shaders/FSRCNNX_x2_16-0-4-1.glsl"
glsl-shaders-append="~~/shaders/KrigBilateral.glsl"
dscale=mitchell
cscale=ewa_lanczos
linear-downscaling=yes

[artcnn]
profile-desc=Artoriuz Convolutional Neural Network
glsl-shaders-append="~~/shaders/ArtCNN_C4F16_DN.glsl"
glsl-shaders-append="~~/shaders/KrigBilateral.glsl"
dscale=mitchell
cscale=ewa_lanczos
linear-downscaling=yes

[fsr]
profile-desc=AMD FidelityFX Super Resolution
glsl-shaders-append="~~/shaders/FSR.glsl"
glsl-shaders-append="~~/shaders/KrigBilateral.glsl"
dscale=mitchell
cscale=ewa_lanczos
linear-downscaling=yes

[nnedi3]
profile-desc=Neural Network Edge Directed Interpolation
glsl-shaders-append="~~/shaders/nnedi3-nns64-win8x4.hook"
glsl-shaders-append="~~/shaders/KrigBilateral.glsl"
dscale=mitchell
cscale=ewa_lanczos
linear-downscaling=yes

[ssim-sr]
profile-desc=SSimSuperResMitchell
glsl-shaders-append="~~/shaders/SSimSuperResMitchell.glsl"
scale=ewa_lanczossharp
dscale=mitchell
cscale=ewa_lanczos
linear-downscaling=yes

[ssim-ds]
profile-desc=SSimDownscaler
glsl-shaders-append="~~/shaders/SSimDownscaler.glsl"
dscale=mitchell
linear-downscaling=no
linear-downscaling=yes

[adaptive-sharpen]
profile-desc=Adaptive Sharpen
glsl-shaders-append="~~/shaders/adaptive-sharpen.glsl"

[noise-static]
profile-desc=Noise Static Luma and Chroma
glsl-shaders-append="~~/shaders/noise_static_luma.hook"
glsl-shaders-append="~~/shaders/noise_static_chroma.hook"


# -------------------------------- #
# ---- Video Quality Profiles ---- #
# -------------------------------- #

[sd]
profile-desc=Shader selection for SD content
profile-cond=height<720
glsl-shaders-clr
profile=fsr
profile=ssim-sr
profile=ssim-ds
profile=noise-static
profile-restore=copy

[hd]
profile-desc=Shader selection for 720p content
profile-cond=height>=720 and height<1080
glsl-shaders-clr
profile=fsr
profile=ssim-sr
profile=ssim-ds
profile=noise-static
profile-restore=copy

[fhd]
profile-desc=Shader selection for 1080p content
profile-cond=height>=1080 and height<1440
glsl-shaders-clr
profile=fsr
profile=ssim-sr
profile=ssim-ds
profile-restore=copy

[qhd]
profile-desc=Shader selection for 1440p content
profile-cond=height>=1440 and height<2160
glsl-shaders-clr
profile=fsr
profile=ssim-sr
profile=ssim-ds
profile-restore=copy

[uhd]
profile-desc=Shader selection for 2160p content
profile-cond=height>=2160
glsl-shaders-clr
profile=fsr
profile=ssim-sr
profile=ssim-ds
profile-restore=copy