# --- UX --- #

-			add volume -2                                       # event: click          # Volume -2
=			add volume 2                                        # event: click          # Volume +2
f           cycle fullscreen            						# event: click      	# Toggle Fullscreen
ESC         set fullscreen no             						# event: click      	# Exit Fullscreen
ESC         show-text "Press `ESC` again to quit"  				# event: double_click   # Exit Confirmation
ESC         quit                         	 					# event: triple_click   # Exit App


# --- Custom Menu --- #

B           	script-binding autosub/download_subs  						# event: click 	#custom-menu: Download Subs 1
Ctrl+b      	script-binding autosub/download_subs2  						# event: click 	#custom-menu: Download Subs 2
F           	script-binding quality-menu/video_formats_toggle  			# event: click 	#custom-menu: Show Video Formats
Alt+f       	script-binding quality-menu/audio_formats_toggle  			# event: click 	#custom-menu: Show Audio Formats
Ctrl+l      	script-binding quality-menu/video_formats_toggle  			# event: click 	#! Stream Quality > Video
Alt+l       	script-binding quality-menu/audio_formats_toggle  			# event: click 	#! Stream Quality > Audio
S           	script-message playlist-manager sort      					# event: click	#! Sort Playlist
F8          	script-message playlist-manager show playlist toggle 		# event: click	# Toggle Playlist
R           	run "cmd.exe" /d /c start "" ${path} ; quit-watch-later		# event: click	#custom-menu: Hot Restart


# --- Image Viewer --- #

# WHEEL_UP    {image} script-binding positioning/cursor-centric-zoom  0.1			# event: click	
# WHEEL_DOWN  {image} script-binding positioning/cursor-centric-zoom -0.1			# event: click	
# 0           {image} no-osd set video-align-y 0; no-osd set video-align-x 0		# event: click	