#--- UX --- #

f           set fullscreen yes             			# event: click    		# Enter Fullscreen
ESC         set fullscreen no             			# event: click    		# Exit Fullscreen
ESC         show-text "Press `ESC` again to quit"  	# event: double_click   # Exit Confirmation
ESC         quit     								# event: triple_click  	# Exit App


#--- Custom Menu --- #

Ctrl+MBTN_RIGHT  script-binding select/context-menu  									# Open Context Menu
b           	script-binding autosub/download_subs  							#custom-menu: Download Subs 1
B           	script-binding autosub/download_subs2  							#custom-menu: Download Subs 2
f           	script-binding quality-menu/video_formats_toggle  				#custom-menu: Show Video Formats
Alt+f       	script-binding quality-menu/audio_formats_toggle  				#custom-menu: Show Audio Formats
Ctrl+l      	script-binding quality-menu/video_formats_toggle  				#! Stream Quality > Video
Alt+l       	script-binding quality-menu/audio_formats_toggle  				#! Stream Quality > Audio
F8          	script-message playlist-manager show playlist toggle  			#custom-menu: Toggle Playlist
R           	run "cmd.exe" /d /c start "" ${path} ; quit-watch-later  		#custom-menu: Hot Restart


#--- Image Viewer --- #

WHEEL_UP    {image} script-binding positioning/cursor-centric-zoom  0.1
WHEEL_DOWN  {image} script-binding positioning/cursor-centric-zoom -0.1
0           {image} no-osd set video-align-y 0; no-osd set video-align-x 0