#--- Shader Profiles --- #

Ctrl+1      no-osd apply-profile "art-cnn"
Ctrl+2      no-osd apply-profile "fsr-cnn-x"
Ctrl+3      no-osd apply-profile "fsr"
Ctrl+4      no-osd apply-profile "ravu"
Ctrl+5      no-osd apply-profile "nnedi3"
Ctrl+6      no-osd apply-profile "ssim-downscaler"
Ctrl+9      no-osd apply-profile "noise-static"
Ctrl+0      no-osd change-list glsl-shaders clr ""; script-message profile_notifier reset ; show-text "GLSL shaders cleared"