compact_mode=no
window_title=no
info_button=yes

hide_timeout=5000
fade_duration=500
osc_on_seek=yes
osc_keep_with_cursor=yes
idle_screen=yes
keep_on_pause=yes

vid_scale=yes
scale_windowed=1.0                  
scale_fullscreen=0.6                
scale_forced_window=1.0